    lemoynese = {
        label = 'Lemoyne Speakeasy',
        type = 'speakeasy',
        defaultDuty = false,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Recruit', payment = 5 },
            ['1'] = { name = 'Staff',   payment = 10 },
            ['2'] = { name = 'Sales',   payment = 15 },
            ['3'] = { name = 'Brewer',  payment = 20 },
            ['4'] = { name = 'Manager', isboss = true, payment = 25 },
        },
    },
    cattailse = {
        label = 'Cattail Pond Speakeasy',
        type = 'speakeasy',
        defaultDuty = false,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Recruit', payment = 5 },
            ['1'] = { name = 'Staff',   payment = 10 },
            ['2'] = { name = 'Sales',   payment = 15 },
            ['3'] = { name = 'Brewer',  payment = 20 },
            ['4'] = { name = 'Manager', isboss = true, payment = 25 },
        },
    },
    newaustinse = {
        label = 'New Austin Speakeasy',
        type = 'speakeasy',
        defaultDuty = false,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Recruit', payment = 5 },
            ['1'] = { name = 'Staff',   payment = 10 },
            ['2'] = { name = 'Sales',   payment = 15 },
            ['3'] = { name = 'Brewer',  payment = 20 },
            ['4'] = { name = 'Manager', isboss = true, payment = 25 },
        },
    },
    hanoverse = {
        label = 'Hanover Speakeasy',
        type = 'speakeasy',
        defaultDuty = false,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Recruit', payment = 5 },
            ['1'] = { name = 'Staff',   payment = 10 },
            ['2'] = { name = 'Sales',   payment = 15 },
            ['3'] = { name = 'Brewer',  payment = 20 },
            ['4'] = { name = 'Manager', isboss = true, payment = 25 },
        },
    },
    manzanitase = {
        label = 'Manzanita Post Speakeasy',
        type = 'speakeasy',
        defaultDuty = false,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Recruit', payment = 5 },
            ['1'] = { name = 'Staff',   payment = 10 },
            ['2'] = { name = 'Sales',   payment = 15 },
            ['3'] = { name = 'Brewer',  payment = 20 },
            ['4'] = { name = 'Manager', isboss = true, payment = 25 },
        },
    },